# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
# source 'git@github.com:your-username/PrivatePod.git' # 私有索引

platform :ios, '10.0' # 这个版本为所有CocoaPods里面`s.ios.deployment_target`支持的最低版本
inhibit_all_warnings!
use_frameworks!

target 'WMMine_Example' do
  pod 'WMMine', :path => '..'

  ## 公共部分《项目耦合》
  pod 'FeatBox', :path => '../../../FeatBox'

  ## 独立公共控件
  pod 'CommonView', :path => '../../../CommonView'
  
  ## 百宝箱工具
  pod 'ProductLib', :path => '../../../ProductLib'
  
  ## 网络组件
  pod 'Networks', :path => '../../../Networks'

end

target 'WMMine_Tests' do
  inherit! :search_paths

end

## https://github.com/CocoaPods/CocoaPods/issues/11402
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            end
        end
    end
    ## Fixed https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3
    installer.generated_projects.each do |project|
       project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          end
       end
    end
end

